### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by timohear** [aquadzn/gpt2-french#2]
Hello, it looks like the demo website isn't working at the moment: 
![image](https://user-images.githubusercontent.com/43105030/68992678-b4be0c00-086e-11ea-86b1-c9a9e95cec0f.png)

**Comment by aquadzn** [comment]
> Hello, it looks like the demo website isn't working at the moment:
> ![image](https://user-images.githubusercontent.com/43105030/68992678-b4be0c00-086e-11ea-86b1-c9a9e95cec0f.png)

Hello @timohear it is normal because I stopped the service.

If you want you can build it locally by downloading [models](https://github.com/aquadzn/gpt2-french/releases/download/v1.1/models.tar.gz), run with Docker and send requests with curl.
