### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by manueltonneau** [aquadzn/gpt2-french#6]
Salut :) 

Je suis en train de fine-tuner différentes versions de GPT-2 sur des tweets de macron et souhaiterais les ajouter au repo. Pour cela, pourrais-tu me donner plus d'informations/les inclure dans le README sur les données d'entrainement que tu as utilisé et les différents paramètres (nb steps, etc..) du modèle? Par ailleurs, comment puis-je ajouter des modèles aux releases?

Merci d'avance!

**Comment by aquadzn** [comment]
Hey, pour les releases il n'y a que moi qui peut les rajouter.

Tu peux m'envoyer ici le README modifié avec tes infos et tu peux uploader ton modèle sur Drive par exemple si tu veux

**Comment by manueltonneau** [comment]
Ca marche! Ca fine-tune encore mais je modifie le README quand c'est terminé et je t'envoie le lien Drive pour accéder au modèle :)
