### ISSUE TITLE
Il y a eu une erreur pendant la génération du texte. Veuillez réessayer!

### ISSUE THREAD

**Issue by bernardlemoullec** [aquadzn/gpt2-french#9]
Hello,

I'm getting an error message every time I try generating text from https://aquadzn.github.io/gpt2-french/

Thanks and regards,
Bernard

**Comment by aquadzn** [comment]
Bonsoir, c'est normal, le service est down mais vous pouvez le faire tourner localement en téléchargeant les [modèles](https://github.com/aquadzn/gpt2-french/releases) dans le dossier `gpt2-model`, en lancant `app.py` et en modifiant [cette url](https://github.com/aquadzn/gpt2-french/blob/master/docs/index.html#L169) avec la votre

**Comment by bernardlemoullec** [comment]
Bonsoir,
Merci pour ces informations.
Je souhaiterais utiliser GPT-2 pour générer du texte en français dans le cadre d'un projet d'études et c'est ainsi que j'ai trouvé votre projet sur GitHub. A ma connaissance, GPT-2 a été entraîné sur un corpus anglophone (WebText), aussi je m'interroge sur la possibilité de générer du texte français de qualité (au minimum syntaxiquement correct)... Pourrais-je vous poser quelques questions sur l'entraînement de votre modèle et les données utilisées s'il vous plaît ?

**Comment by aquadzn** [comment]
#8

**Comment by aquadzn** [comment]
> Bonsoir,
> Merci pour ces informations.
> Je souhaiterais utiliser GPT-2 pour générer du texte en français dans le cadre d'un projet d'études et c'est ainsi que j'ai trouvé votre projet sur GitHub. A ma connaissance, GPT-2 a été entraîné sur un corpus anglophone (WebText), aussi je m'interroge sur la possibilité de générer du texte français de qualité (au minimum syntaxiquement correct)... Pourrais-je vous poser quelques questions sur l'entraînement de votre modèle et les données utilisées s'il vous plaît ?

Oui c'est ça un mélange de Wikipedia, Reddit et autres

Pour pouvoir obtenir de bons résultats en français il faudrait déjà un bon corpus équivalent en français et une très grosse puissance de calcul (plusieurs milliers d'euros)

cf #8 pour les données utilisées

**Comment by bernardlemoullec** [comment]
Merci beaucoup !
